package-lock.json, package.json
=> chore: install element plus

src/App.vue
=> style: added custom styling

src/components/Form.vue, src/composables/rules/useRegistrationRule.ts
remove unnecessary logs, comments, lines and fix warnings
=> fix: deprecated methods and form warnings

src/interface/card.ts, src/router/index.ts, src/stores/game-store.ts, src/utils/createDeck.ts, src/utils/shuffleDeck.ts, src/views/in-game/TestZoneView.vue
review card partial logic for shuffling of cards, creating deck, betting and drawing of third card
=> add: pairing and randomization of card,creatng deck,draw third card, higher or lower stakes, and betting

components.d.ts, src/components/PlayerHand.vue, src/components/PlayingCard.vue, src/views/in-game/GameZoneView.vue
created two components. 
1. Playing cards that is reusable that will show individual card based on card ID.
2. player hands is for players deck hand that uses playing cards to display 3 cards for each unique player
=> add: Implemented player hands and playingcards as component

src/components/PlayerHand.vue, src/views/in-game/GameZoneView.vue
This PR refactors and improves the styling and mechanics of the GameZone table. It introduces the PlayerHand and PlayingCards components, integrating them into the game for better modularity and code organization. Additionally, it connects the player counter and player registration information to the GameZone, ensuring that player data and active player states are accurately reflected in the UI. These changes enhance maintainability, readability, and the overall user experience.
- Refactored and improved the …
=> add: update PlayerHand styles for improved layout and responsiveness

src/components/GameCta.vue
=> add: fix fold

src/components/BetForm.vue, src/components/CashFlow.vue, src/components/CreditForm.vue, src/components/GameCta.vue, src/stores/game-store.ts, src/utils/modalUtils.ts, src/views/in-game/GameZoneView.vue
=> demo-gamev2

src/components/dialog/GameOverModal.vue, src/interface/game-state.ts, src/stores/game-store.ts
=> fix: removed unnecessary properties

src/assets/styles/game-zone/game-zone.scss, src/utils/gameplay/pop-ups/modalUtil.ts, src/views/in-game/GameZoneView.vue
=> feat: add modal styles and logic for win, lose, and fold states

src/composables/game/useGameHistory.ts, src/views/in-game/GameZoneView.vue
=> added: added empty state in history

src/components/dialog/HowToPlayDialog.vue, src/components/dialog/MainMenuDialog.vue, src/components/utilities/EventsHistory.vue, src/eventBus.ts, src/views/in-game/GameZoneView.vue
=> Fix/ready fixed the 'How to Play' timer pausing

src/components/dialog/NotEnoughPlayers.vue, src/components/forms/CreditForm.vue
=> fix: add credit ang gameOver feedbacks

src/stores/game-store.ts, src/utils/gameplay/pop-ups/modalUtil.ts
=> add: add penalty when players run out of time

src/components/currency/CommunalPot.vue, src/components/game-table/PlayerPosition.vue
=> fix: fix credits and pot display

src/views/LandingPageView.vue
=> style: added back the bg

src/components/currency/CreditActions.vue
=> fix: change the cta-styling to dyanmic

src/components/game-table/PlayerHand.vue
=> fix: card styling on the table in deafult view

src/components/forms/PlayerForm.vue, src/composables/rules/useRegistrationRule.ts, src/stores/game-store.ts, src/utils/gameplay/pop-ups/modalUtil.ts
=> fix: penalty remove and registration rules

src/main.ts
=> fix: added nav guarad
